author: yanm1ng # 作者
description: DD's Home
keyword: hexo-theme, vuejs
favicon: https://kiva.coding.net/p/ddhammer.fun/d/ddhammer.fun/git/raw/master/css/images/dd.webp

excerpt_link: 阅读全文

menu:
 Home: /
 Post: /posts/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: nonstop-story
gitment_repo: ddhammer.fun
gitment_oauth_id: c65c479a3282ef71e914
gitment_oauth_secret: 1bab3c3e3354861f37264c43eb275cb595057edd

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: https://kiva.coding.net/p/ddhammer.fun/d/ddhammer.fun/git/raw/master/css/images/hololive1st.jpg
  avatar: https://kiva.coding.net/p/ddhammer.fun/d/ddhammer.fun/git/raw/master/css/images/dd.webp
  description: "不要停下来啊！！！"
  github_username: nonstop-story

# MathJax Support
mathjax:
  enable: false
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
  #cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=default

vtubers:
  - name: 泠鸢 Yousa
    mid: 282994

  - name: 白上吹雪Offical
    mid: 332704117

  - name: 夏色祭Official
    mid: 336731767

  - name: 湊-阿库娅Official
    mid: 375504219

  - name: 神楽Mea_Official
    mid: 349991143

  - name: 新科娘Official
    mid: 451066708

  - name: 神楽七奈Official
    mid: 386900246

  - name: 兔田佩克拉Official
    mid: 443305053
  
  - name: 赤井心Official
    mid: 339567211

  - name: 樱巫女Official
    mid: 366690056
  
  - name: 润羽露西娅Official
    mid: 443300418

  - name: 夜空梅露Official
    mid: 389856447
  
  - name: 物述有栖Official
    mid: 434565011

  - name: 陆婉莹GodRiku
    mid: 337827661
  
  - name: 高槻律official
    mid: 6055289

  - name: 战斗吧歌姬官方账号
    mid: 364225566

  - name: Overidea_China
    mid: 18149131

  - name: 帕里_Paryi
    mid: 1576121
  
  - name: 花园Serena
    mid: 380829248

  - name: 黑桃影
    mid: 456368455

  - name: 角卷绵芽Official
    mid: 491474050

  - name: 白神遥Haruka
    mid: 477332594

  - name: 进击的冰糖
    mid: 198297

  - name: 時雨羽衣Official
    mid: 2601367

  - name: 佐久間ねむOfficial
    mid: 476903292             

  - name: 有栖Mana_Official
    mid: 3149619

  - name: 夢乃栞Yumeno_Shiori
    mid: 372984197

  - name: 紫咲诗音Official
    mid: 389857640

  - name: 常暗永远Official
    mid: 491474051

  - name: 犬山玉姬Official
    mid: 12362451

  - name: 桐生可可Official
    mid: 491474049

  - name: 天音彼方Official
    mid: 491474048 

  - name: 希薇娅Civia 
    mid: 354411419

  - name: Soy_Official
    mid: 2191383  

  - name: 时乃空Official
    mid: 286179206

  - name: 白银诺艾尔Official
    mid: 454733056

  - name: 百鬼绫目Official
    mid: 389858027

  - name: 癒月巧可Official
    mid: 389858754            