author: yanm1ng # 作者
description: DD's Home
keyword: hexo-theme, vuejs
favicon: https://coding.net/u/Kiva/p/Kiva.coding.me/git/raw/master/css/images/logo.png

excerpt_link: 阅读全文

menu:
 Home: /
 Post: /posts/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: imkiva
gitment_repo: ddhammer.fun
gitment_oauth_id: c65c479a3282ef71e914
gitment_oauth_secret: 1bab3c3e3354861f37264c43eb275cb595057edd

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://coding.net/u/Kiva/p/Kiva.coding.me/git/raw/master/css/images/logo.png
  description: "Talk is cheap, show me the code."
  github_username: imkiva
  weibo_username: NNRRK
  zhihu_username: kiva-76

# MathJax Support
mathjax:
  enable: false
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
  #cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=default

vtubers:
  - name: 泠鸢 Yousa
    avatar: /css/avatars/yousa.jpg
    room: https://live.bilibili.com/593

  - name: 白上吹雪 Offical
    avatar: /css/avatars/fubuki.jpg
    room: https://live.bilibili.com/11588230

  - name: 夏色祭Official
    avatar: /css/avatars/natsuri.jpg
    room: https://live.bilibili.com/13946381

  - name: 湊-阿库娅Official
    avatar: /css/avatars/aqua.jpg
    room: https://live.bilibili.com/14917277

  - name: 神楽Mea_Official
    avatar: /css/avatars/mea.jpg
    room: https://live.bilibili.com/12235923

  - name: 新科娘Official
    avatar: /css/avatars/xinke.jpg
    room: https://live.bilibili.com/21602686

  - name: 神楽七奈Official
    avatar: /css/avatars/nanane.jpeg
    room: https://live.bilibili.com/21304638

  - name: 兔田佩克拉Official
    avatar: /css/avatars/pekora.jpeg
    room: https://live.bilibili.com/21560356
  
  - name: 赤井心Official
    avatar: /css/avatars/xinxin.jpg
    room: https://live.bilibili.com/14275133

  - name: 樱巫女Official
    avatar: /css/avatars/sakura.jpg
    room: https://live.bilibili.com/21144047
  
  - name: 润羽露西娅Official
    avatar: /css/avatars/lucia.jpg
    room: https://live.bilibili.com/21545232

  - name: 夜空梅露Official
    avatar: /css/avatars/meilu.jpeg
    room: https://live.bilibili.com/21131813
  
  - name: 物述有栖Official
    avatar: /css/avatars/wushu.jpeg
    room: https://live.bilibili.com/21449083

  - name: 陆婉莹GodRiku
    avatar: /css/avatars/godriku.jpg
    room: https://live.bilibili.com/11575621
  
  - name: 高槻律official
    avatar: /css/avatars/lv.jpg
    room: https://live.bilibili.com/947447

  - name: 战斗吧歌姬官方账号
    avatar: /css/avatars/fighting.jpg
    room: https://live.bilibili.com/14578426

  - name: Overidea_China
    avatar: /css/avatars/overidea.jpg
    room: https://live.bilibili.com/704808

  - name: 帕里_Paryi
    avatar: /css/avatars/paryi.jpeg
    room: https://live.bilibili.com/4895312
  

